---
- hosts: all
  become: yes
  vars:
   ntp_server: [pool.ntp.org, at.pool.ntp.org, ts1.univie.ac.at]
  tasks:

  - name: Install packages
    apt:
      name:
      - ntp
      state: latest
  - name: Update Timezone to Europe/Vienna
    ansible.builtin.copy:
       content: 'Europe/Vienna'
       dest: /etc/timezone
       owner: root
       group: root
       mode: 0644

  - name: Reconfigure Timezone Data
    ansible.builtin.shell: dpkg-reconfigure -f noninteractive tzdata


  - name: deploy ntp.conf
    template:
     src: /home/mark/ntp/ntp.conf.j2
     dest: /etc/ntp.conf
     owner: root
     group: root
     mode: 0644
    notify:
     - restart ntp
  handlers:
  - name: restart ntp
    service: name=ntp state=restarted

